apiVersion: apps/v1
kind: Deployment
metadata:
  name: curl
  namespace: clear
spec:
  selector:
    matchLabels:
      app: clear-curl
  template:
    metadata:
      labels:
        app: clear-curl
    spec:
      containers:
      - name: curl
        image: curlimages/curl:7.86.0
        command: [/bin/sleep, 3d]
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
